Contact form feature
gids-dadi/Portfolio-setup-and-mobile-version-skeleton-repeat- pull request #3
Opened 2022-02-22 22:17 UTC by gids-dadi

The branch feature-contact-form adds a contact form to the repo, with Formspree action to collect information from data

2022-02-22 23:07 UTC, Whoistolu requested changes
Hi @gids-dadi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

#### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-22 23:07 UTC, Whoistolu commented on index.html
> +          method="POST"
- [x] [REQUIRED] You have done a good job by implementing the method value to be `POST` and action as a `formspree` value, however, I will urge you to crosscheck and ensure you have input the correct value for the action because the submissions I have made on the form has been unsuccessful.
- [x] [REQUIRED] Please check this out:
- Add a little more margin between the `textarea` and the `SeeProject` Button.
- Increase the margin between the `SeeProject` Button and the social icons just as it has been provided in the template.
- Please ensure that we have equal spaces between the social icons.

Your Implementation   |  Figma Design
:-------------------------:|:-------------------------:
![Screenshot from 2022-02-22 23-29-59](https://user-images.githubusercontent.com/58692590/155233601-744b0d88-c2ce-42e9-925c-13a2a65a423b.png) | ![Screenshot from 2022-02-22 23-30-02](https://user-images.githubusercontent.com/58692590/155233699-1b516fd0-b210-42a2-ab92-b17d996d3010.png)

2022-02-22 23:07 UTC, Whoistolu commented on index.html
> +          </textarea
- [ ] [REQUIRED] Great implementations here, however, it is required that the message input has maxlength="500" attribute. Please go-ahead to implement this.

2022-02-22 23:07 UTC, Whoistolu commented on index.html
> +          <button class="contact-buttton" type="button">See Project</button>
- [x] [REQUIRED] Please note that the submit button should have a type="submit". Please implement it as this may also be a reason why the form has refused to submit successfully.

2022-02-22 23:07 UTC, Whoistolu commented on index.html
> +              />
- [x] [REQUIRED] One of the requirements states that the name input should have `maxlength="30"` attribute. Kindly implement this.

2022-02-22 23:07 UTC, Whoistolu commented on style.css
> +}
- [ ] [REQUIRED] You have done an awesome job implementing the button interaction, however, you need to implement for `enabled`, `hover`, `pressed`, and `disabled`. Please fix this.
![Screenshot from 2022-02-23 00-01-33](https://user-images.githubusercontent.com/58692590/155234575-895f240d-f754-4059-89d0-47ce6ea03c35.png)

2022-02-23 15:25 UTC, gids-dadi commented on index.html
> +          </textarea
Done

2022-02-23 15:25 UTC, gids-dadi commented on index.html
> +          <button class="contact-buttton" type="button">See Project</button>
Noted! Thank you

2022-02-23 15:26 UTC, gids-dadi commented on index.html
> +              />
Done

2022-02-23 15:27 UTC, gids-dadi commented on style.css
> +}
Noted

2022-02-23 16:04 UTC, Amrhub approved these changes
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi @gids-dadi, 👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

## Highlights ✅ 
Highly organized and clean code ✔️ 👨🏻‍💻 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-23 16:22 UTC, merged